# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe299147465a19897143126b163787a979f6148a3bea6ede9d654f5d4caa42246033d6edcb4aa919adcb547ebd56a0c191beda2a084a28242a1d57da3aebf645

test:
  secret_key_base: 265b3f4d265c84c018849cb98b2a3607e1f78e9d5c53839e54fd9327c25cd70774840e67436584fadf666f3bf271b63ae59ef7461e6e880f17819126759ea3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
